---
title: "AITA"
author: "Tianle Yu"
date: "2023-05-15"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r, echo=FALSE}
df = read.csv("./data/controversialAll1000.csv")
plot(df$upvote_ratio,df$comments)
boxplot(df$comments~df$upvote_ratio,col=c("red","green","purple"))
plot(df$up,df$comments, xlim = c(- 1, 20), ylim = c(- 1, 500))
df = read.csv("./data/topAll1000.csv")
df2 = read.csv("./data/controversialAll1000.csv")
df3 = rbind(df,df2)

print("Summary of top 1000")
summary(df[c(4,6,8)])
print("Summary of top 1000 controversial")
summary(df2[c(4,6,8)])
print("Summary of all 2000")
summary(df3[c(4,6,8)])
```

```{r, echo=FALSE}
mean_comments <- tapply(df3$comments, df3$up, mean)

# Create a new data frame for plotting
df_grouped <- data.frame(
  upvotes = as.numeric(names(mean_comments)),
  mean_comments = mean_comments
)

# Sort by upvotes
df_grouped <- df_grouped[order(df_grouped$upvotes),]

# Plot the data
plot(df_grouped$upvotes, df_grouped$mean_comments, type = "l", 
     xlab = "Upvotes", ylab = "Average Comments", 
     main = "Average Comments per Upvote")
```

```{r, echo=FALSE}
# Calculate the mean of comments for each upvote count
mean_comments <- tapply(df3$comments, df3$up, mean)

# Create a new data frame for plotting
df_grouped <- data.frame(
  upvotes = as.numeric(names(mean_comments)),
  mean_comments = mean_comments
)

# Sort by upvotes
df_grouped <- df_grouped[order(df_grouped$upvotes),]

# Fit a loess curve to the data
loess_fit <- loess(mean_comments ~ upvotes, data = df_grouped)

# Predict the loess curve at a sequence of points
loess_predictions <- predict(loess_fit, newdata = data.frame(upvotes = df_grouped$upvotes))

# Plot the data
plot(df_grouped$upvotes, df_grouped$mean_comments, 
     xlab = "Upvotes", ylab = "Average Comments", 
     main = "Average Comments per Upvote", type = "n")  # empty plot
lines(df_grouped$up, loess_predictions, col = "blue")  # loess curve


```

```{r, echo=FALSE}
# boxplot(df$comments,df2$comments)
par(mar = c(4, 8, 4.1, 2.1))
barplot(table(df$flair),las=2,horiz = TRUE, main="Number of flairs in top 1000 posts")
barplot(table(df2$flair),las=2,horiz = TRUE, main="Number of flairs in top 1000 controversial posts")
par(mar = c(4, 8, 4.1, 2.1))
barplot(table(df3$flair),las=2,horiz = TRUE, main="Number of flairs in 2000 posts")
print("Correlation Score")
print(cor(df3$up, df3$comments))
abline(lm(df3$up ~ df3$comments))
```

```{r, echo=FALSE}
print(cor(df3$up, df3$comments))
plot(df3$comments~df3$up, pch=020, xlab="Upvotes", ylab="Comments", main="Linear Regression of Comments over Upvotes")
print(lm(df3$comments~df3$up))
abline(lm(df3$comments~df3$up))
```
```{r, echo=FALSE}

# boxplot(df3[df3$flair=="Asshole","comments"],df3[df3$flair=="Not the A-hole","comments"])

df_sub <- df3[df3$flair %in% c("Asshole", "Not the A-hole"),]

# Use the boxplot() function with a formula argument
boxplot(comments ~ flair, data = df_sub, 
        xlab = "Flair", ylab = "Comments", 
        main = "Comments by Flair",
        names = c("Asshole", "Not the A-hole"),
        ylim = c (0,8000),
        col=c("red","green","purple"))

# Use the boxplot() function with a formula argument
boxplot(up ~ flair, data = df_sub, 
        xlab = "Flair", ylab = "Upvotes", 
        main = "Upvotes by Flair",
        names = c("Asshole", "Not the A-hole"),
        ylim = c (0,50000),
        col=c("red","green","purple"))

boxplot(upvote_ratio ~ flair, data = df_sub, 
        xlab = "Flair", ylab = "Upvote Ratio", 
        main = "Upvote Ratio by Flair",
        names = c("Asshole", "Not the A-hole"),
        ylim = c (0,1),
        col=c("red","green","purple"))
```
```{r}

```